In [ ]:
Importing the libraries

#to read the dataframe
import pandas as pd
Reading the dataset as a dataframe

# Reading dataframe
df = pd.read_csv('AB_NYC.csv')

df.head()
id	name	host_id	host_name	neighbourhood_group	neighbourhood	latitude	longitude	room_type	price	minimum_nights	number_of_reviews	last_review	reviews_per_month	calculated_host_listings_count	availability_365
0	2539	Clean & quiet apt home by the park	2787	John	Brooklyn	Kensington	40.64749	-73.97237	Private room	149.0	1	9	2018-10-19	0.21	6	365
1	2595	Skylit Midtown Castle	2845	Jennifer	Manhattan	Midtown	40.75362	-73.98377	Entire home/apt	225.0	1	45	2019-05-21	0.38	2	355
2	3647	THE VILLAGE OF HARLEM....NEW YORK !	4632	Elisabeth	Manhattan	Harlem	40.80902	-73.94190	Private room	150.0	3	0	NaN	NaN	1	365
3	3831	Cozy Entire Floor of Brownstone	4869	LisaRoxanne	Brooklyn	Clinton Hill	40.68514	-73.95976	Entire home/apt	89.0	1	270	2019-07-05	4.64	1	194
4	5022	Entire Apt: Spacious Studio/Loft by central park	7192	Laura	Manhattan	East Harlem	40.79851	-73.94399	Entire home/apt	80.0	10	9	2018-11-19	0.10	1	0
Discovering the dataset

#show the number of cells in the dataframe
print("dataset size: ", df.size)
​
#show the number of records (rows) in the dataframe
print("number of hosts: ", len(df))
​
#show the number of features (coulmns) in the dataframe
print("number of features: ", len(df.columns))
dataset size:  782320
number of hosts:  48895
number of features:  16

df.dtypes
id                                  int64
name                               object
host_id                             int64
host_name                          object
neighbourhood_group                object
neighbourhood                      object
latitude                          float64
longitude                         float64
room_type                          object
price                             float64
minimum_nights                      int64
number_of_reviews                   int64
last_review                        object
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
dtype: object
Activities
Let's clean the dataset.
1. Find out the missing values in each column

col_missing_values = df.isna().sum()
2. Drop the column reviews_per_month as it has many values missing and we will not use it

df.drop(columns='reviews_per_month',inplace=True)
3. Drop the rows having more than 1 missing value

df_rows_dropped = df.dropna(thresh=df.shape[1]-1,axis=0)
4. Fill the 21 missing values in host_name with the value Airbnb

host_total = df.host_name.fillna('Airbnb')
5. Check if any name in the Column host_name has digit(s) or number(s) in it

df.host_name.str.isnumeric().sum()
7

df.host_name.str.isalpha().sum()
44950
6. Fill the 2 missing values of the column price with the mean of the column

mean_df_price = df.price.fillna(df.price.mean())
7. Fill all missing values in last_review using forward filling method

ffill_review = df.last_review.ffill()
8. Select duplicate hosts in a dataframe based on name, host_id, and price columns

duplicate_hosts = df[df.duplicated(subset=['name','host_id','price'], keep=False)]
10. Drop duplicates while keeping the first non-NaN value based on name, host_id, and price columns

df_unique_hosts = df.drop_duplicates(subset=['name','host_id','price'],keep='first')
11. How many users in the Column room_type are Private room?

private_room_counts = df.loc[df.room_type=='Private room','room_type'].count()
12. Find the words in Column name which contain the substring park

mask = df.name.str.contains('park')

names_having_park = mask
13. Replace the neighbourhood having Kitchen with Restaurant

kitchen_to_restaurant = df.neighbourhood.replace('Kitchen','Restaurant', regex=True)
14. Split the strings in the room_type column at   (space) to find whether it is room or home/apt

roomOrhome = df.room_type.apply(lambda a: a.split()[1])

roomOrhome
0            room
1        home/apt
2            room
3        home/apt
4        home/apt
           ...
48890        room
48891        room
48892    home/apt
48893        room
48894        room
Name: room_type, Length: 48895, dtype: object
15. Clean the column availability_365 by removing invalid values

df_invalid_availability_365 = df.loc[df.availability_365==0]
17. Clean the column minimum_nights by removing outliers

Nights_plot = df['minimum_nights'].plot(kind='hist')
Nights_plot.set_yscale('log')
Nights_plot.set_xlabel('minimum_nights')
Nights_plot.set_ylabel('Frequency')
Text(0, 0.5, 'Frequency')


df_nights['Min_Nights_cleaned'] = ((df_nights['minimum_nights'] - df_nights['minimum_nights'].mean()) /  df_nights['minimum_nights'].std()).abs() >= 43
​
18. Clean the column price by removing outliers

df_Price = df.copy()
Price_plot = df_Price['price'].plot(kind='box')
Price_plot.set_yscale('log')


q1 = df.price.quantile(.25)
q2 = df.price.median()
q3 = df.price.quantile(.75)
iqr = q3-q1
whisker = iqr*1.5
df_Price['Price_cleaned'] = (df.price<q1-whisker )|(df.price>q3+whisker