In [ ]:


import pandas as pd
import seaborn as sns
Reading the datasets

movies_df = pd.read_csv('movies.csv')
ratings_df = pd.read_csv('ratings.csv')
tags_df = pd.read_csv('tags.csv')
links_df = pd.read_csv('links.csv')

movies_df.head()
movieId	title	genres
0	1	Toy Story (1995)	Adventure|Animation|Children|Comedy|Fantasy
1	2	Jumanji (1995)	Adventure|Children|Fantasy
2	3	Grumpier Old Men (1995)	Comedy|Romance
3	4	Waiting to Exhale (1995)	Comedy|Drama|Romance
4	5	Father of the Bride Part II (1995)	Comedy

ratings_df.head()
userId	movieId	rating	timestamp
0	1	1	4.0	964982703
1	1	3	4.0	964981247
2	1	6	4.0	964982224
3	1	47	5.0	964983815
4	1	50	5.0	964982931

tags_df.head()
userId	movieId	tag	timestamp
0	2	60756	funny	1445714994
1	2	60756	Highly quotable	1445714996
2	2	60756	will ferrell	1445714992
3	2	89774	Boxing story	1445715207
4	2	89774	MMA	1445715200

links_df.head()
movieId	imdbId	tmdbId
0	1	114709	862.0
1	2	113497	8844.0
2	3	113228	15602.0
3	4	114885	31357.0
4	5	113041	11862.0
Brief Data Analysis

sns.histplot(data=ratings_df, x='rating')
<Axes: xlabel='rating', ylabel='Count'>


sns.boxplot(data=ratings_df, x='rating')
<Axes: xlabel='rating'>


#show the number of cells in movies dataframe
print("movies dataframe size: ", movies_df.size)
​
#show the number of records (rows) in movies dataframe
print("number of movies: ", len(movies_df))
movies dataframe size:  29226
number of movies:  9742

movies_df.dtypes
movieId     int64
title      object
genres     object
dtype: object

ratings_df.dtypes
userId         int64
movieId        int64
rating       float64
timestamp      int64
dtype: object

tags_df.dtypes
userId        int64
movieId       int64
tag          object
timestamp     int64
dtype: object

links_df.dtypes
movieId      int64
imdbId       int64
tmdbId     float64
dtype: object
Activities
6. Drop duplicate movies based on title and keep the first occurence

movies_df.drop_duplicates(['title'],keep='first',inplace=True)
7. Merge movies_df & ratings_df with an inner join on movieId

movies_ratings_df = movies_df.merge(ratings_df,on='movieId')
8. Use the merged movies_ratings_df dataframe to calculate the average rating for each movie

avg_ratings = movies_ratings_df.groupby('title')['rating'].agg('mean')
10. Merge movies_df & tags_df with a left join on movieId.

movies_tags_df = movies_df.merge(tags_df,how='left',on='movieId')
11. Use the merged dataframe movies_tags_df to select the movies with no tags

movies_with_no_tags = movies_tags_df[movies_tags_df['tag'].isnull()]
12. Merge tags_df & ratings_df using the movie ID and the user ID

tags_ratings_df = tags_df.merge(ratings_df,on=['movieId','userId'],how='outer',suffixes=('_tags','_ratings'))
13. Merge movies_df dataframe & tag_counts series with the left dataframe on genres & the right series on its index

tag_counts = tags_df.tag.value_counts().rename("tag_count")

 movies_tags_counts_df = pd.merge(movies_df, tag_counts, left_on='genres', right_index=True)
​
14. Merge movies_df dataframe & rating_counts series using outer join with the left dataframe on movieId & the right series on its index

# number of times each movie has been rated
rating_counts = ratings_df.movieId.value_counts().rename("rating_count")

movies_ratings_counts_df = movies_df.merge(rating_counts,how='outer',left_on='movieId',right_index=True)
15. Use the movies_ratings_counts_df dataframe to select the movies with no ratings

movies_with_no_ratings = movies_ratings_counts_df[movies_ratings_counts_df.rating_count.isnull()]