In [ ]:


import pandas as pd

df = pd.read_csv('vgsales.csv')
df.head()
Rank	Name	Platform	Year	Genre	Publisher	NA_Sales	EU_Sales	JP_Sales	Other_Sales	Global_Sales
0	1	Wii Sports	Wii	2006.0	Sports	Nintendo	41.49	29.02	3.77	8.46	82.74
1	2	Super Mario Bros.	NES	1985.0	Platform	Nintendo	29.08	3.58	6.81	0.77	40.24
2	3	Mario Kart Wii	Wii	2008.0	Racing	Nintendo	15.85	12.88	3.79	3.31	35.82
3	4	Wii Sports Resort	Wii	2009.0	Sports	Nintendo	15.75	11.01	3.28	2.96	33.00
4	5	Pokemon Red/Pokemon Blue	GB	1996.0	Role-Playing	Nintendo	11.27	8.89	10.22	1.00	31.37

df.info()
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  object
 2   Platform      16598 non-null  object
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  object
 5   Publisher     16540 non-null  object
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 1.4+ MB

df.describe()
Rank	Year	NA_Sales	EU_Sales	JP_Sales	Other_Sales	Global_Sales
count	16598.000000	16327.000000	16598.000000	16598.000000	16598.000000	16598.000000	16598.000000
mean	8300.605254	2006.406443	0.264667	0.146652	0.077782	0.048063	0.537441
std	4791.853933	5.828981	0.816683	0.505351	0.309291	0.188588	1.555028
min	1.000000	1980.000000	0.000000	0.000000	0.000000	0.000000	0.010000
25%	4151.250000	2003.000000	0.000000	0.000000	0.000000	0.000000	0.060000
50%	8300.500000	2007.000000	0.080000	0.020000	0.000000	0.010000	0.170000
75%	12449.750000	2010.000000	0.240000	0.110000	0.040000	0.040000	0.470000
max	16600.000000	2020.000000	41.490000	29.020000	10.220000	10.570000	82.740000

df.columns
Index(['Rank', 'Name', 'Platform', 'Year', 'Genre', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales'],
      dtype='object')
Activities
1. Filter Games by Genre

# try your code here
sports_df = df.loc[df.Genre=='Sports']
2. Filter Games by Sales in North America

# Try your code here
na_sales_df = df.loc[df.NA_Sales>1]
3. Filter Games by Platform and Year

# Try your code here
ps2_2005_df = df.loc[(df.Platform=='PS2')&(df.Year==2005)]
4. Filter Games by Global Sales Range

# Try your code here
global_sales_df = df.loc[(df.Global_Sales>=20)&(df.Global_Sales<=30)]
5. Filter Games by Publisher and Genre

# Try your code here
nintendo_action_df =df.loc[(df.Publisher=='Nintendo')&(df.Genre=='Action')]
6. Filter Games by Multiple Genres

# Try your code here
action_sports_df = df.loc[df.Genre.isin(['Action','Sports'])]
7. Select Games by Multiple Criteria

# Try your code here
​
ps2_action_sports_df = df.loc[(df.Genre.isin(['Action','Sports']))&(df.Platform=='PS2')&(df.Global_Sales>=5)&(df.Global_Sales<=30)]
8. Filter Games by Sales

# Try your code here
​
filtered_query_df = df.loc[(df.Global_Sales>=5)&(df.Global_Sales<=30)]
9. Filter Games by Platform and Critic Score

# Try your code here
​
query_ps2_df = df.query('Platform == "PS2" and Global_Sales>5')
10. Filtering Rows and Columns

# Try your code here
query_rows_cols_df = df.query('Year>2000 and Global_Sales>5')[['Name','Platform','Year','Global_Sales']]
11. Filter the dataset to include games with a platform of either PS4 or NES

# Try your code here
query_rows_cols_df2 = df.loc[df.Platform.isin(['PS4','NES']),['Name','NA_Sales','EU_Sales']]
12. Get the top 10 games from all regions

# Try your code here
top10_df = df.head(10)[['Name','NA_Sales','EU_Sales','JP_Sales','Other_Sales','Global_Sales']]
13. Calculate the average sales in North America

# Try your code here
df.loc[df.Genre=='Action','NA_Sales'].mean()
0.2647255729794934
14. Find the genre with the highest sales in Japan

# Try your code here
df.groupby('Genre')['JP_Sales'].sum().idxmax()
'Role-Playing'
15. Determine the average sales in Europe for the game published by Electronic Arts

# Try your code here
df.loc[df.Publisher=='Electronic Arts','EU_Sales'].mean()
0.27481125092524056
16. Find all the games released between 2005 and 2010 (inclusive) with multiple condition

# Try your code here
games_2005_2010 = df.query('2005 <= Year <= 2010 and Genre == "Action" and Global_Sales > 5')
​
17. Find the top 10 games with multiple filters

# Try your code here
top_10_shooter_2010 = df.query('Genre=="Shooter" and Year>2010').sort_values(by='NA_Sales',ascending=False).head(10)[['Name', 'NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales']]

top_10_shooter_2010
Name	NA_Sales	EU_Sales	JP_Sales	Other_Sales	Global_Sales
29	Call of Duty: Modern Warfare 3	9.03	4.28	0.13	1.32	14.76
35	Call of Duty: Black Ops II	8.25	4.30	0.07	1.12	13.73
61	Call of Duty: Ghosts	6.72	2.63	0.04	0.82	10.21
65	Halo 4	6.63	2.36	0.04	0.73	9.76
33	Call of Duty: Black Ops 3	5.77	5.81	0.35	2.31	14.24
37	Call of Duty: Modern Warfare 3	5.54	5.82	0.49	1.62	13.46
34	Call of Duty: Black Ops II	4.99	5.88	0.65	2.52	14.03
101	Call of Duty: Black Ops 3	4.52	2.09	0.01	0.67	7.30
99	Battlefield 3	4.46	2.13	0.06	0.69	7.34
67	Call of Duty: Ghosts	4.09	3.73	0.38	1.38	9.59
18. Fill in the blanks to complete the code for conditional filtering and aggregation operations

# Try your code here
sales_2012_europe = df.loc[df['Year'] == 2012, 'EU_Sales'].sum()
The End!