In [ ]:


import pandas as pd

# Read the dataset into a DataFrame
df = pd.read_csv('penguins_cleaned.csv')
df
species	island	culmen_length_mm	culmen_depth_mm	flipper_length_mm	body_mass_g	sex
0	Adelie	Torgersen	39.1	18.7	181.0	3750.0	MALE
1	Adelie	Torgersen	39.5	17.4	186.0	3800.0	FEMALE
2	Adelie	Torgersen	40.3	18.0	195.0	3250.0	FEMALE
3	Adelie	Torgersen	36.7	19.3	193.0	3450.0	FEMALE
4	Adelie	Torgersen	39.3	20.6	190.0	3650.0	MALE
...	...	...	...	...	...	...	...
328	Gentoo	Biscoe	47.2	13.7	214.0	4925.0	FEMALE
329	Gentoo	Biscoe	46.8	14.3	215.0	4850.0	FEMALE
330	Gentoo	Biscoe	50.4	15.7	222.0	5750.0	MALE
331	Gentoo	Biscoe	45.2	14.8	212.0	5200.0	FEMALE
332	Gentoo	Biscoe	49.9	16.1	213.0	5400.0	MALE
333 rows Ã— 7 columns

# Convert all columns to pandas Series
species = df['species']
island = df['island']
culmen_length_mm = df['culmen_length_mm']
culmen_depth_mm = df['culmen_depth_mm']
flipper_length_mm = df['flipper_length_mm']
body_mass_g = df['body_mass_g']
gender = df['sex']

print("Species: ", species)
Species:  0      Adelie
1      Adelie
2      Adelie
3      Adelie
4      Adelie
        ...
328    Gentoo
329    Gentoo
330    Gentoo
331    Gentoo
332    Gentoo
Name: species, Length: 333, dtype: object

print("Island: ", island)
Island:  0      Torgersen
1      Torgersen
2      Torgersen
3      Torgersen
4      Torgersen
         ...
328       Biscoe
329       Biscoe
330       Biscoe
331       Biscoe
332       Biscoe
Name: island, Length: 333, dtype: object

print("Culmen Length (mm): ", culmen_length_mm)
Culmen Length (mm):  0      39.1
1      39.5
2      40.3
3      36.7
4      39.3
       ...
328    47.2
329    46.8
330    50.4
331    45.2
332    49.9
Name: culmen_length_mm, Length: 333, dtype: float64

print("Culmen Depth (mm): ", culmen_depth_mm)
Culmen Depth (mm):  0      18.7
1      17.4
2      18.0
3      19.3
4      20.6
       ...
328    13.7
329    14.3
330    15.7
331    14.8
332    16.1
Name: culmen_depth_mm, Length: 333, dtype: float64

print("Flipper Length (mm): ", flipper_length_mm)
Flipper Length (mm):  0      181.0
1      186.0
2      195.0
3      193.0
4      190.0
       ...
328    214.0
329    215.0
330    222.0
331    212.0
332    213.0
Name: flipper_length_mm, Length: 333, dtype: float64

print("Body Mass (g): ", body_mass_g)
Body Mass (g):  0      3750.0
1      3800.0
2      3250.0
3      3450.0
4      3650.0
        ...
328    4925.0
329    4850.0
330    5750.0
331    5200.0
332    5400.0
Name: body_mass_g, Length: 333, dtype: float64

print("Gender: ", gender)
Gender:  0        MALE
1      FEMALE
2      FEMALE
3      FEMALE
4        MALE
        ...
328    FEMALE
329    FEMALE
330      MALE
331    FEMALE
332      MALE
Name: sex, Length: 333, dtype: object
Activities
1. Add a constant value.

body_mass_g_plus_100 = body_mass_g+100
2. Subtract the 'culmen_length_mm' series from the 'flipper_length_mm' series

length_difference = flipper_length_mm-culmen_length_mm
3. Multiply to series

double_culmen_depth_mm = culmen_depth_mm*2
4. Raise the 'flipper_length_mm' series to the power

flipper_length_mm_squared = flipper_length_mm**2
5. Calculate the mean of the 'culmen_length_mm' series and subtract it from each value in the series

culmen_length_mm_mean_centered = culmen_length_mm-culmen_length_mm.mean()
6. Concatenate the 'species' and 'gender' series

species_and_gender = species+'-'+gender
7. Perform element-wise addition

culmen_length_plus_depth_mm = culmen_length_mm+culmen_depth_mm
8. Sort culmen_length_mm in descending order

culmen_length_mm_sorted = culmen_length_mm.sort_values(ascending=False)
9. Divide flipper_length_mm by culmen_length_mm

length_ratio = flipper_length_mm/culmen_length_mm
The End!